@startuml
title LifeGame

namespace Points {
  interface PointInterface {
    x: number
    y: number
  }

  class Point {
    x: number
    y: number
  }
  Point -|> Points.PointInterface
}

namespace Cells {
  enum CellState {
    Live,
    On
  }

  interface CellInterface {
    state: CellState
    kill()
    revive()
    toggle(): CellState
  }
}

namespace Worlds {
  interface WorldInterface {
    getCell(point: PointInterface): Cell
    setCell(point: PointInterface, cell: Cell)
  }
}

interface LifeGameInterface {
  forward(step: number = 1)
}
@enduml